import { join } from 'node:path';
import { AgentRuntime } from '@hezo/shared';
import { buildJudgeScriptForRuntime } from '../stop-hook-prompt';
import { bearerEnvVarName } from './toml';
import type { McpHttpDescriptor, McpInjection, McpInjectionFile, RuntimeMcpAdapter } from './types';

/**
 * Prime Agent MCP + completeness-gate injector.
 *
 * Everything lands under `$PRIME_AGENT_CODING_AGENT_DIR`, which relocates the
 * CLI's whole data root (settings.json, sessions, auth.json) to the per-run
 * directory the runner creates. There is no `--mcp-config`-style flag, so that
 * env var is the only isolation mechanism — hence `requiresHomeDir: true`.
 *
 * **This adapter writes more than a config file, and it has to.** Prime Agent
 * does not surface MCP tools as model tools: the protocol runs Python-side in
 * its IPython kernel, and a server only becomes reachable when a Python package
 * subclassing `rlm.McpIntegration` is loaded as a skill. A `settings.json`
 * `mcpServers` entry alone registers the endpoint host-side and gives the agent
 * nothing. So for each server this emits BOTH the settings entry and a
 * generated skill package, and points the CLI at them with `--skill`.
 *
 * Only HTTP descriptors are emitted. Prime Agent's host drops non-HTTP entries
 * outright ("stdio servers are not yet wired through to the kernel"), so a
 * stdio connector would be silently ignored — better to leave it out of the
 * config than to write something the CLI discards.
 */

interface PrimeAgentHttpEntry {
	type: 'http';
	url: string;
	headers?: Record<string, string>;
	bearerTokenEnvVar?: string;
}

interface PrimeAgentSettings {
	mcpServers?: Record<string, PrimeAgentHttpEntry>;
	telemetry: { enabled: false };
}

const JUDGE_SCRIPT_BASENAME = 'stop-hook-judge.mjs';

/** Where generated MCP skill packages live inside the per-run home. */
const SKILLS_DIRNAME = 'skills';

/**
 * A Python identifier safe to `import`. MCP server names are operator-supplied
 * connector slugs, so they can carry hyphens and dots that would make the
 * generated package unimportable.
 */
export function pythonModuleName(serverName: string): string {
	const cleaned = serverName.replace(/[^0-9a-zA-Z_]/g, '_').replace(/^(?=\d)/, '_');
	return cleaned.toLowerCase() || '_mcp';
}

/**
 * The Python package that makes one MCP server callable from the kernel.
 *
 * Tool discovery is Prime Agent's job: `McpIntegration.__getattr__` fetches the
 * server's tool list on first use and binds each one as an async method, so the
 * agent writes `await hezo.create_comment(...)` with the real tool names and
 * this file never has to know them.
 *
 * The bearer arrives via `bearer_token_env` — an env var NAME, never the value —
 * which is what keeps the token out of every file the agent can read and lets
 * the egress proxy substitute a `__HEZO_SECRET_*__` placeholder at request time.
 */
export function buildMcpSkillModule(serverName: string, url: string, hasBearer: boolean): string {
	const className = pythonModuleName(serverName)
		.split('_')
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
	const bearerLine = hasBearer
		? `\n    bearer_token_env = ${JSON.stringify(bearerEnvVarName(serverName))}`
		: '';
	return `"""Generated by Hezo. Tools are auto-discovered from the MCP server at runtime."""

from __future__ import annotations

from rlm import McpIntegration

__all__ = [${JSON.stringify(className)}, ${JSON.stringify(pythonModuleName(serverName))}]


class ${className}(McpIntegration):
    server = ${JSON.stringify(serverName)}
    url = ${JSON.stringify(url)}${bearerLine}


${pythonModuleName(serverName)} = ${className}()

# Names the kernel bootstrap probes to decide whether a module is itself a
# callable skill. Forwarding them would return an MCP tool stub and the module
# would be wrapped as callable, breaking \`await ${pythonModuleName(serverName)}.<tool>()\` dispatch.
_RESERVED = {"run", "__wrapped__", "__call__"}


def __getattr__(name: str):
    if name.startswith("_") or name in _RESERVED:
        raise AttributeError(name)
    return getattr(${pythonModuleName(serverName)}, name)
`;
}

/** The SKILL.md frontmatter Prime Agent reads to decide whether to load a skill. */
export function buildMcpSkillDoc(serverName: string): string {
	const mod = pythonModuleName(serverName);
	return `---
name: ${mod}
description: Hezo-managed MCP integration for "${serverName}". Tools are discovered from the server at runtime.
---

# ${serverName}

Call this server's tools from the IPython kernel. The tool set comes from the
server, not from this file, so discover before you call rather than assuming
names.

\`\`\`python
import ${mod}

# What is available
for tool in await ${mod}.list_tools():
    print(tool["name"], "-", tool["description"])

# What one tool expects (rendered from its JSON Schema)
help(${mod}.some_tool)

# Call it; keyword args must match the tool's input schema
result = await ${mod}.some_tool(example="value")
\`\`\`

Every tool is an \`async\` method, so always \`await\`. Results come back as
parsed Python - a \`dict\` for structured output, otherwise a string - so there
is nothing to \`json.loads\`.
`;
}

function buildHttpEntry(d: McpHttpDescriptor): PrimeAgentHttpEntry {
	const entry: PrimeAgentHttpEntry = { type: 'http', url: d.url };
	if (d.headers && Object.keys(d.headers).length > 0) entry.headers = { ...d.headers };
	// By env-var NAME, never the value: `bearerTokenStorage: 'env-var'` and
	// `validateInjection` together enforce that no `Bearer …` reaches a file.
	if (d.bearerToken) entry.bearerTokenEnvVar = bearerEnvVarName(d.name);
	return entry;
}

export const primeAgentAdapter: RuntimeMcpAdapter = {
	capabilities: {
		transport: 'streamable-http',
		bearerTokenStorage: 'env-var',
		requiresHomeDir: true,
	},
	build(descriptors, ctx): McpInjection {
		if (!ctx.hostHomeDir || !ctx.containerHomeDir) {
			throw new Error('prime-agent mcp adapter requires hostHomeDir and containerHomeDir');
		}

		// stdio servers are dropped by Prime Agent's host, so never emit them.
		const httpDescriptors = descriptors.filter((d): d is McpHttpDescriptor => d.kind === 'http');

		const settings: PrimeAgentSettings = { telemetry: { enabled: false } };
		if (httpDescriptors.length > 0) {
			settings.mcpServers = Object.fromEntries(
				httpDescriptors.map((d) => [d.name, buildHttpEntry(d)]),
			);
		}

		const files: McpInjectionFile[] = [
			{
				hostPath: join(ctx.hostHomeDir, 'settings.json'),
				mode: 0o600,
				contents: `${JSON.stringify(settings, null, 2)}\n`,
			},
			{
				hostPath: join(ctx.hostHomeDir, JUDGE_SCRIPT_BASENAME),
				mode: 0o700,
				// Non-null: JUDGE_SPECS carries an entry for this runtime. An empty
				// script would install a gate that always passes, which is worse than
				// the loud failure of a missing file.
				contents: buildJudgeScriptForRuntime(AgentRuntime.PrimeAgent) ?? '',
			},
		];

		const cliArgs: string[] = [];
		const envEntries: string[] = [];
		for (const d of httpDescriptors) {
			const mod = pythonModuleName(d.name);
			const pkgHost = join(ctx.hostHomeDir, SKILLS_DIRNAME, mod);
			files.push(
				{
					hostPath: join(pkgHost, 'SKILL.md'),
					mode: 0o600,
					contents: buildMcpSkillDoc(d.name),
				},
				{
					hostPath: join(pkgHost, 'src', mod, '__init__.py'),
					mode: 0o600,
					contents: buildMcpSkillModule(d.name, d.url, Boolean(d.bearerToken)),
				},
			);
			cliArgs.push('--skill', join(ctx.containerHomeDir, SKILLS_DIRNAME, mod));
			if (d.bearerToken) envEntries.push(`${bearerEnvVarName(d.name)}=${d.bearerToken}`);
		}

		return { cliArgs, envEntries, files };
	},
};
