-- Add the xAI provider (`x_ai`) to the `ai_provider` enum so operators can
-- configure xAI's Grok Build CLI as an AI coding-agent provider.
--
-- This is a purely additive enum extension. Postgres 12+ (PGlite is PG16)
-- permits ALTER TYPE ... ADD VALUE inside a transaction as long as the new
-- value is not *used* in the same transaction — this migration only adds it, so
-- it is safe under the runner's per-migration BEGIN/COMMIT. The enum is
-- referenced by several columns (ai_provider_configs.provider,
-- tasks.model_override_provider, cost_entries.provider, and the run table's
-- provider), none of which need rewriting: existing rows keep their values and
-- the new value simply becomes selectable.
ALTER TYPE ai_provider ADD VALUE IF NOT EXISTS 'x_ai';
