import {
	DATE_FORMATS,
	type DateFormat,
	formatDateIn,
	formatMoneyUsd,
	LANGUAGE_LABELS,
	LANGUAGES,
	type Language,
	type LocaleSettings,
	NUMBER_FORMATS,
	type NumberFormat,
} from '@hezo/shared';
import { Check, Languages } from 'lucide-react';
import { useI18n } from '../../lib/i18n';

/**
 * The locale picker - language, date format, and currency format on one screen.
 *
 * A single component with two hosts (the onboarding step and the header
 * button's dialog), so the operator edits their locale through exactly the same
 * form wherever they reach it.
 *
 * Every option renders a **live preview** rather than an abstract name: the date
 * options show today's date in each ordering and the currency options show one
 * amount punctuated three ways, so the choice needs no explanation. The preview
 * is generated by the same shared formatters the app renders with, so what the
 * operator picks is exactly what they will see.
 */

/** A sample amount whose thousands separator and decimal mark are both visible. */
const SAMPLE_CENTS = 123456;

interface LocaleFormProps {
	value: LocaleSettings;
	onChange: (next: LocaleSettings) => void;
	/** Disable every control while a save is in flight. */
	disabled?: boolean;
	/** Rendered at the bottom - the host supplies its own submit affordance. */
	children?: React.ReactNode;
}

function FieldLabel({ htmlFor, children }: { htmlFor: string; children: React.ReactNode }) {
	return (
		<label
			htmlFor={htmlFor}
			className="flex items-center gap-1.5 text-[13px] font-medium text-text-1 mb-1.5"
		>
			{children}
		</label>
	);
}

/**
 * A radio-style option row. Radio semantics (not buttons) so the group is
 * navigable by arrow key and announced as a single choice.
 */
function OptionRow({
	name,
	checked,
	onSelect,
	disabled,
	label,
	preview,
}: {
	name: string;
	checked: boolean;
	onSelect: () => void;
	disabled?: boolean;
	label: string;
	preview?: string;
}) {
	return (
		<label
			className={`flex items-center gap-3 rounded-md border px-3 py-2 text-[13px] transition-colors ${
				disabled ? 'opacity-60' : 'cursor-pointer'
			} ${
				checked
					? 'border-border-strong bg-surface-3 text-text-1'
					: 'border-border text-text-2 hover:text-text-1 hover:bg-surface-3'
			}`}
		>
			<input
				type="radio"
				name={name}
				checked={checked}
				onChange={onSelect}
				disabled={disabled}
				className="sr-only"
			/>
			<span className="flex-1 text-left">{label}</span>
			{preview && <span className="tabular-nums text-text-2">{preview}</span>}
			{checked && <Check className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />}
		</label>
	);
}

export function LocaleForm({ value, onChange, disabled, children }: LocaleFormProps) {
	const { t } = useI18n();
	// A fixed date would go stale in a screenshot; today's is what the operator
	// will actually be reading tomorrow.
	const sampleDate = new Date();

	return (
		<div className="space-y-5">
			<div>
				<FieldLabel htmlFor="locale-language">
					{t('locale.language.label')}
					{/* The same translate glyph the pre-auth locale button carries - see
					    locale-switcher.tsx for why it is that and not a globe. Decorative:
					    the label text already names the field. */}
					<Languages className="h-3.5 w-3.5 shrink-0 text-text-2" aria-hidden="true" />
				</FieldLabel>
				<select
					id="locale-language"
					value={value.language}
					disabled={disabled}
					onChange={(e) => onChange({ ...value, language: e.target.value as Language })}
					className="w-full rounded-md border border-border bg-surface px-3 py-2 text-[13px] text-text-1 disabled:opacity-60"
				>
					{LANGUAGES.map((language) => (
						<option key={language} value={language}>
							{LANGUAGE_LABELS[language]}
						</option>
					))}
				</select>
			</div>

			<fieldset>
				<legend className="block text-[13px] font-medium text-text-1 mb-1.5">
					{t('locale.dateFormat.label')}
				</legend>
				<div className="space-y-1.5">
					{DATE_FORMATS.map((dateFormat: DateFormat) => (
						<OptionRow
							key={dateFormat}
							name="locale-date-format"
							checked={value.date_format === dateFormat}
							onSelect={() => onChange({ ...value, date_format: dateFormat })}
							disabled={disabled}
							label={formatDateIn(sampleDate, { ...value, date_format: dateFormat })}
						/>
					))}
				</div>
			</fieldset>

			<fieldset>
				<legend className="block text-[13px] font-medium text-text-1 mb-1.5">
					{t('locale.numberFormat.label')}
				</legend>
				<div className="space-y-1.5">
					{NUMBER_FORMATS.map((numberFormat: NumberFormat) => (
						<OptionRow
							key={numberFormat}
							name="locale-number-format"
							checked={value.number_format === numberFormat}
							onSelect={() => onChange({ ...value, number_format: numberFormat })}
							disabled={disabled}
							label={formatMoneyUsd(SAMPLE_CENTS, numberFormat)}
						/>
					))}
				</div>
				<p className="mt-1.5 text-[12px] text-text-2">{t('locale.numberFormat.hint')}</p>
			</fieldset>

			{children}
		</div>
	);
}
