import { waitFor } from '@testing-library/react';
import { expect, test } from 'vitest';
import { renderApp } from './helpers/render';
import { type SeededWorkspace, seedWorkspace } from './helpers/seed';

test('renders default team_context for an Engineer', async () => {
	let ws!: SeededWorkspace;
	let engineerId = '';
	const { findByTestId, router } = await renderApp({
		initialPath: '/',
		seed: async () => {
			ws = await seedWorkspace();
			const engineer = ws.agents.find((a) => a.slug === 'engineer');
			if (!engineer) throw new Error('engineer missing from seeded workspace');
			engineerId = engineer.id;
		},
	});

	await router.navigate({
		to: '/projects/$projectId/agents/$agentId/settings',
		params: { projectId: ws.internalSlug, agentId: engineerId },
	});

	const section = await findByTestId('agent-team-context', undefined, { timeout: 20_000 });
	await waitFor(
		() => {
			expect(section.textContent ?? '').toContain('@architect');
		},
		{ timeout: 20_000 },
	);
});

test('attribution caption renders beneath the section', async () => {
	let ws!: SeededWorkspace;
	let agentId = '';
	const { findByTestId, router } = await renderApp({
		initialPath: '/',
		seed: async () => {
			ws = await seedWorkspace();
			const agent = ws.agents.find((a) => a.slug === 'engineer') ?? ws.agents[0];
			agentId = agent.id;
		},
	});

	await router.navigate({
		to: '/projects/$projectId/agents/$agentId/settings',
		params: { projectId: ws.internalSlug, agentId },
	});

	const caption = await findByTestId('agent-team-context-attribution', undefined, {
		timeout: 20_000,
	});
	expect(caption.textContent ?? '').toContain('Auto-generated by the Captain');
});

test('section appears between Reports To and Monthly Budget controls in DOM order', async () => {
	let ws!: SeededWorkspace;
	let agentId = '';
	const { findByTestId, findByText, container, router } = await renderApp({
		initialPath: '/',
		seed: async () => {
			ws = await seedWorkspace();
			const agent = ws.agents.find((a) => a.slug === 'engineer') ?? ws.agents[0];
			agentId = agent.id;
		},
	});

	await router.navigate({
		to: '/projects/$projectId/agents/$agentId/settings',
		params: { projectId: ws.internalSlug, agentId },
	});

	const section = await findByTestId('agent-team-context', undefined, { timeout: 20_000 });
	const reportsToLabel = await findByText('Reports To');
	const budgetLabel = await findByText(/Monthly Budget/);

	// Assert DOM order via compareDocumentPosition since happy-dom lacks layout.
	const all = Array.from(container.querySelectorAll('*')) as HTMLElement[];
	const reportsIdx = all.indexOf(reportsToLabel);
	const sectionIdx = all.indexOf(section);
	const budgetIdx = all.indexOf(budgetLabel);
	expect(reportsIdx).toBeGreaterThanOrEqual(0);
	expect(sectionIdx).toBeGreaterThan(reportsIdx);
	expect(budgetIdx).toBeGreaterThan(sectionIdx);
});
