/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as InboxIndexRouteImport } from './routes/inbox/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as TeamsNewRouteImport } from './routes/teams/new'
import { Route as SettingsAiProvidersRouteImport } from './routes/settings/ai-providers'
import { Route as TeamsTeamIdRouteRouteImport } from './routes/teams/$teamId/route'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as TeamsTeamIdProjectsIndexRouteImport } from './routes/teams/$teamId/projects/index'
import { Route as TeamsTeamIdKbIndexRouteImport } from './routes/teams/$teamId/kb/index'
import { Route as TeamsTeamIdIssuesIndexRouteImport } from './routes/teams/$teamId/issues/index'
import { Route as TeamsTeamIdInboxIndexRouteImport } from './routes/teams/$teamId/inbox/index'
import { Route as TeamsTeamIdGoalsIndexRouteImport } from './routes/teams/$teamId/goals/index'
import { Route as TeamsTeamIdAgentsIndexRouteImport } from './routes/teams/$teamId/agents/index'
import { Route as TeamsTeamIdSettingsGeneralRouteImport } from './routes/teams/$teamId/settings/general'
import { Route as TeamsTeamIdSettingsCredentialsRouteImport } from './routes/teams/$teamId/settings/credentials'
import { Route as TeamsTeamIdSettingsConnectionsRouteImport } from './routes/teams/$teamId/settings/connections'
import { Route as TeamsTeamIdSettingsAuditLogRouteImport } from './routes/teams/$teamId/settings/audit-log'
import { Route as TeamsTeamIdIssuesIssueIdRouteImport } from './routes/teams/$teamId/issues/$issueId'
import { Route as TeamsTeamIdAgentsHireRouteImport } from './routes/teams/$teamId/agents/hire'
import { Route as TeamsTeamIdProjectsProjectIdRouteRouteImport } from './routes/teams/$teamId/projects/$projectId/route'
import { Route as TeamsTeamIdAgentsAgentIdRouteRouteImport } from './routes/teams/$teamId/agents/$agentId/route'
import { Route as TeamsTeamIdProjectsProjectIdIndexRouteImport } from './routes/teams/$teamId/projects/$projectId/index'
import { Route as TeamsTeamIdAgentsAgentIdIndexRouteImport } from './routes/teams/$teamId/agents/$agentId/index'
import { Route as TeamsTeamIdProjectsProjectIdDocumentsRouteImport } from './routes/teams/$teamId/projects/$projectId/documents'
import { Route as TeamsTeamIdProjectsProjectIdContainerRouteImport } from './routes/teams/$teamId/projects/$projectId/container'
import { Route as TeamsTeamIdAgentsAgentIdSettingsRouteImport } from './routes/teams/$teamId/agents/$agentId/settings'
import { Route as TeamsTeamIdProjectsProjectIdSettingsIndexRouteImport } from './routes/teams/$teamId/projects/$projectId/settings/index'
import { Route as TeamsTeamIdProjectsProjectIdIssuesIndexRouteImport } from './routes/teams/$teamId/projects/$projectId/issues/index'
import { Route as TeamsTeamIdAgentsAgentIdExecutionsIndexRouteImport } from './routes/teams/$teamId/agents/$agentId/executions/index'
import { Route as TeamsTeamIdProjectsProjectIdIssuesIssueIdRouteImport } from './routes/teams/$teamId/projects/$projectId/issues/$issueId'
import { Route as TeamsTeamIdAgentsAgentIdExecutionsRunIdRouteImport } from './routes/teams/$teamId/agents/$agentId/executions/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiProvidersRoute = SettingsAiProvidersRouteImport.update({
  id: '/settings/ai-providers',
  path: '/settings/ai-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRouteRoute = TeamsTeamIdRouteRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdProjectsIndexRoute =
  TeamsTeamIdProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdKbIndexRoute = TeamsTeamIdKbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdIssuesIndexRoute = TeamsTeamIdIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdInboxIndexRoute = TeamsTeamIdInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdGoalsIndexRoute = TeamsTeamIdGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdAgentsIndexRoute = TeamsTeamIdAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdSettingsGeneralRoute =
  TeamsTeamIdSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdSettingsCredentialsRoute =
  TeamsTeamIdSettingsCredentialsRouteImport.update({
    id: '/settings/credentials',
    path: '/settings/credentials',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdSettingsConnectionsRoute =
  TeamsTeamIdSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdSettingsAuditLogRoute =
  TeamsTeamIdSettingsAuditLogRouteImport.update({
    id: '/settings/audit-log',
    path: '/settings/audit-log',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdIssuesIssueIdRoute =
  TeamsTeamIdIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdAgentsHireRoute = TeamsTeamIdAgentsHireRouteImport.update({
  id: '/agents/hire',
  path: '/agents/hire',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdProjectsProjectIdRouteRoute =
  TeamsTeamIdProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdAgentsAgentIdRouteRoute =
  TeamsTeamIdAgentsAgentIdRouteRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => TeamsTeamIdRouteRoute,
  } as any)
const TeamsTeamIdProjectsProjectIdIndexRoute =
  TeamsTeamIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeamsTeamIdProjectsProjectIdRouteRoute,
  } as any)
const TeamsTeamIdAgentsAgentIdIndexRoute =
  TeamsTeamIdAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeamsTeamIdAgentsAgentIdRouteRoute,
  } as any)
const TeamsTeamIdProjectsProjectIdDocumentsRoute =
  TeamsTeamIdProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => TeamsTeamIdProjectsProjectIdRouteRoute,
  } as any)
const TeamsTeamIdProjectsProjectIdContainerRoute =
  TeamsTeamIdProjectsProjectIdContainerRouteImport.update({
    id: '/container',
    path: '/container',
    getParentRoute: () => TeamsTeamIdProjectsProjectIdRouteRoute,
  } as any)
const TeamsTeamIdAgentsAgentIdSettingsRoute =
  TeamsTeamIdAgentsAgentIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => TeamsTeamIdAgentsAgentIdRouteRoute,
  } as any)
const TeamsTeamIdProjectsProjectIdSettingsIndexRoute =
  TeamsTeamIdProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => TeamsTeamIdProjectsProjectIdRouteRoute,
  } as any)
const TeamsTeamIdProjectsProjectIdIssuesIndexRoute =
  TeamsTeamIdProjectsProjectIdIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => TeamsTeamIdProjectsProjectIdRouteRoute,
  } as any)
const TeamsTeamIdAgentsAgentIdExecutionsIndexRoute =
  TeamsTeamIdAgentsAgentIdExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => TeamsTeamIdAgentsAgentIdRouteRoute,
  } as any)
const TeamsTeamIdProjectsProjectIdIssuesIssueIdRoute =
  TeamsTeamIdProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => TeamsTeamIdProjectsProjectIdRouteRoute,
  } as any)
const TeamsTeamIdAgentsAgentIdExecutionsRunIdRoute =
  TeamsTeamIdAgentsAgentIdExecutionsRunIdRouteImport.update({
    id: '/executions/$runId',
    path: '/executions/$runId',
    getParentRoute: () => TeamsTeamIdAgentsAgentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteRouteWithChildren
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/teams/new': typeof TeamsNewRoute
  '/home/': typeof HomeIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/agents/$agentId': typeof TeamsTeamIdAgentsAgentIdRouteRouteWithChildren
  '/teams/$teamId/projects/$projectId': typeof TeamsTeamIdProjectsProjectIdRouteRouteWithChildren
  '/teams/$teamId/agents/hire': typeof TeamsTeamIdAgentsHireRoute
  '/teams/$teamId/issues/$issueId': typeof TeamsTeamIdIssuesIssueIdRoute
  '/teams/$teamId/settings/audit-log': typeof TeamsTeamIdSettingsAuditLogRoute
  '/teams/$teamId/settings/connections': typeof TeamsTeamIdSettingsConnectionsRoute
  '/teams/$teamId/settings/credentials': typeof TeamsTeamIdSettingsCredentialsRoute
  '/teams/$teamId/settings/general': typeof TeamsTeamIdSettingsGeneralRoute
  '/teams/$teamId/agents/': typeof TeamsTeamIdAgentsIndexRoute
  '/teams/$teamId/goals/': typeof TeamsTeamIdGoalsIndexRoute
  '/teams/$teamId/inbox/': typeof TeamsTeamIdInboxIndexRoute
  '/teams/$teamId/issues/': typeof TeamsTeamIdIssuesIndexRoute
  '/teams/$teamId/kb/': typeof TeamsTeamIdKbIndexRoute
  '/teams/$teamId/projects/': typeof TeamsTeamIdProjectsIndexRoute
  '/teams/$teamId/agents/$agentId/settings': typeof TeamsTeamIdAgentsAgentIdSettingsRoute
  '/teams/$teamId/projects/$projectId/container': typeof TeamsTeamIdProjectsProjectIdContainerRoute
  '/teams/$teamId/projects/$projectId/documents': typeof TeamsTeamIdProjectsProjectIdDocumentsRoute
  '/teams/$teamId/agents/$agentId/': typeof TeamsTeamIdAgentsAgentIdIndexRoute
  '/teams/$teamId/projects/$projectId/': typeof TeamsTeamIdProjectsProjectIdIndexRoute
  '/teams/$teamId/agents/$agentId/executions/$runId': typeof TeamsTeamIdAgentsAgentIdExecutionsRunIdRoute
  '/teams/$teamId/projects/$projectId/issues/$issueId': typeof TeamsTeamIdProjectsProjectIdIssuesIssueIdRoute
  '/teams/$teamId/agents/$agentId/executions/': typeof TeamsTeamIdAgentsAgentIdExecutionsIndexRoute
  '/teams/$teamId/projects/$projectId/issues/': typeof TeamsTeamIdProjectsProjectIdIssuesIndexRoute
  '/teams/$teamId/projects/$projectId/settings/': typeof TeamsTeamIdProjectsProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/teams/new': typeof TeamsNewRoute
  '/home': typeof HomeIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/agents/hire': typeof TeamsTeamIdAgentsHireRoute
  '/teams/$teamId/issues/$issueId': typeof TeamsTeamIdIssuesIssueIdRoute
  '/teams/$teamId/settings/audit-log': typeof TeamsTeamIdSettingsAuditLogRoute
  '/teams/$teamId/settings/connections': typeof TeamsTeamIdSettingsConnectionsRoute
  '/teams/$teamId/settings/credentials': typeof TeamsTeamIdSettingsCredentialsRoute
  '/teams/$teamId/settings/general': typeof TeamsTeamIdSettingsGeneralRoute
  '/teams/$teamId/agents': typeof TeamsTeamIdAgentsIndexRoute
  '/teams/$teamId/goals': typeof TeamsTeamIdGoalsIndexRoute
  '/teams/$teamId/inbox': typeof TeamsTeamIdInboxIndexRoute
  '/teams/$teamId/issues': typeof TeamsTeamIdIssuesIndexRoute
  '/teams/$teamId/kb': typeof TeamsTeamIdKbIndexRoute
  '/teams/$teamId/projects': typeof TeamsTeamIdProjectsIndexRoute
  '/teams/$teamId/agents/$agentId/settings': typeof TeamsTeamIdAgentsAgentIdSettingsRoute
  '/teams/$teamId/projects/$projectId/container': typeof TeamsTeamIdProjectsProjectIdContainerRoute
  '/teams/$teamId/projects/$projectId/documents': typeof TeamsTeamIdProjectsProjectIdDocumentsRoute
  '/teams/$teamId/agents/$agentId': typeof TeamsTeamIdAgentsAgentIdIndexRoute
  '/teams/$teamId/projects/$projectId': typeof TeamsTeamIdProjectsProjectIdIndexRoute
  '/teams/$teamId/agents/$agentId/executions/$runId': typeof TeamsTeamIdAgentsAgentIdExecutionsRunIdRoute
  '/teams/$teamId/projects/$projectId/issues/$issueId': typeof TeamsTeamIdProjectsProjectIdIssuesIssueIdRoute
  '/teams/$teamId/agents/$agentId/executions': typeof TeamsTeamIdAgentsAgentIdExecutionsIndexRoute
  '/teams/$teamId/projects/$projectId/issues': typeof TeamsTeamIdProjectsProjectIdIssuesIndexRoute
  '/teams/$teamId/projects/$projectId/settings': typeof TeamsTeamIdProjectsProjectIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteRouteWithChildren
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/teams/new': typeof TeamsNewRoute
  '/home/': typeof HomeIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/agents/$agentId': typeof TeamsTeamIdAgentsAgentIdRouteRouteWithChildren
  '/teams/$teamId/projects/$projectId': typeof TeamsTeamIdProjectsProjectIdRouteRouteWithChildren
  '/teams/$teamId/agents/hire': typeof TeamsTeamIdAgentsHireRoute
  '/teams/$teamId/issues/$issueId': typeof TeamsTeamIdIssuesIssueIdRoute
  '/teams/$teamId/settings/audit-log': typeof TeamsTeamIdSettingsAuditLogRoute
  '/teams/$teamId/settings/connections': typeof TeamsTeamIdSettingsConnectionsRoute
  '/teams/$teamId/settings/credentials': typeof TeamsTeamIdSettingsCredentialsRoute
  '/teams/$teamId/settings/general': typeof TeamsTeamIdSettingsGeneralRoute
  '/teams/$teamId/agents/': typeof TeamsTeamIdAgentsIndexRoute
  '/teams/$teamId/goals/': typeof TeamsTeamIdGoalsIndexRoute
  '/teams/$teamId/inbox/': typeof TeamsTeamIdInboxIndexRoute
  '/teams/$teamId/issues/': typeof TeamsTeamIdIssuesIndexRoute
  '/teams/$teamId/kb/': typeof TeamsTeamIdKbIndexRoute
  '/teams/$teamId/projects/': typeof TeamsTeamIdProjectsIndexRoute
  '/teams/$teamId/agents/$agentId/settings': typeof TeamsTeamIdAgentsAgentIdSettingsRoute
  '/teams/$teamId/projects/$projectId/container': typeof TeamsTeamIdProjectsProjectIdContainerRoute
  '/teams/$teamId/projects/$projectId/documents': typeof TeamsTeamIdProjectsProjectIdDocumentsRoute
  '/teams/$teamId/agents/$agentId/': typeof TeamsTeamIdAgentsAgentIdIndexRoute
  '/teams/$teamId/projects/$projectId/': typeof TeamsTeamIdProjectsProjectIdIndexRoute
  '/teams/$teamId/agents/$agentId/executions/$runId': typeof TeamsTeamIdAgentsAgentIdExecutionsRunIdRoute
  '/teams/$teamId/projects/$projectId/issues/$issueId': typeof TeamsTeamIdProjectsProjectIdIssuesIssueIdRoute
  '/teams/$teamId/agents/$agentId/executions/': typeof TeamsTeamIdAgentsAgentIdExecutionsIndexRoute
  '/teams/$teamId/projects/$projectId/issues/': typeof TeamsTeamIdProjectsProjectIdIssuesIndexRoute
  '/teams/$teamId/projects/$projectId/settings/': typeof TeamsTeamIdProjectsProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teams/$teamId'
    | '/settings/ai-providers'
    | '/teams/new'
    | '/home/'
    | '/inbox/'
    | '/settings/'
    | '/teams/'
    | '/teams/$teamId/'
    | '/teams/$teamId/agents/$agentId'
    | '/teams/$teamId/projects/$projectId'
    | '/teams/$teamId/agents/hire'
    | '/teams/$teamId/issues/$issueId'
    | '/teams/$teamId/settings/audit-log'
    | '/teams/$teamId/settings/connections'
    | '/teams/$teamId/settings/credentials'
    | '/teams/$teamId/settings/general'
    | '/teams/$teamId/agents/'
    | '/teams/$teamId/goals/'
    | '/teams/$teamId/inbox/'
    | '/teams/$teamId/issues/'
    | '/teams/$teamId/kb/'
    | '/teams/$teamId/projects/'
    | '/teams/$teamId/agents/$agentId/settings'
    | '/teams/$teamId/projects/$projectId/container'
    | '/teams/$teamId/projects/$projectId/documents'
    | '/teams/$teamId/agents/$agentId/'
    | '/teams/$teamId/projects/$projectId/'
    | '/teams/$teamId/agents/$agentId/executions/$runId'
    | '/teams/$teamId/projects/$projectId/issues/$issueId'
    | '/teams/$teamId/agents/$agentId/executions/'
    | '/teams/$teamId/projects/$projectId/issues/'
    | '/teams/$teamId/projects/$projectId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/ai-providers'
    | '/teams/new'
    | '/home'
    | '/inbox'
    | '/settings'
    | '/teams'
    | '/teams/$teamId'
    | '/teams/$teamId/agents/hire'
    | '/teams/$teamId/issues/$issueId'
    | '/teams/$teamId/settings/audit-log'
    | '/teams/$teamId/settings/connections'
    | '/teams/$teamId/settings/credentials'
    | '/teams/$teamId/settings/general'
    | '/teams/$teamId/agents'
    | '/teams/$teamId/goals'
    | '/teams/$teamId/inbox'
    | '/teams/$teamId/issues'
    | '/teams/$teamId/kb'
    | '/teams/$teamId/projects'
    | '/teams/$teamId/agents/$agentId/settings'
    | '/teams/$teamId/projects/$projectId/container'
    | '/teams/$teamId/projects/$projectId/documents'
    | '/teams/$teamId/agents/$agentId'
    | '/teams/$teamId/projects/$projectId'
    | '/teams/$teamId/agents/$agentId/executions/$runId'
    | '/teams/$teamId/projects/$projectId/issues/$issueId'
    | '/teams/$teamId/agents/$agentId/executions'
    | '/teams/$teamId/projects/$projectId/issues'
    | '/teams/$teamId/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/teams/$teamId'
    | '/settings/ai-providers'
    | '/teams/new'
    | '/home/'
    | '/inbox/'
    | '/settings/'
    | '/teams/'
    | '/teams/$teamId/'
    | '/teams/$teamId/agents/$agentId'
    | '/teams/$teamId/projects/$projectId'
    | '/teams/$teamId/agents/hire'
    | '/teams/$teamId/issues/$issueId'
    | '/teams/$teamId/settings/audit-log'
    | '/teams/$teamId/settings/connections'
    | '/teams/$teamId/settings/credentials'
    | '/teams/$teamId/settings/general'
    | '/teams/$teamId/agents/'
    | '/teams/$teamId/goals/'
    | '/teams/$teamId/inbox/'
    | '/teams/$teamId/issues/'
    | '/teams/$teamId/kb/'
    | '/teams/$teamId/projects/'
    | '/teams/$teamId/agents/$agentId/settings'
    | '/teams/$teamId/projects/$projectId/container'
    | '/teams/$teamId/projects/$projectId/documents'
    | '/teams/$teamId/agents/$agentId/'
    | '/teams/$teamId/projects/$projectId/'
    | '/teams/$teamId/agents/$agentId/executions/$runId'
    | '/teams/$teamId/projects/$projectId/issues/$issueId'
    | '/teams/$teamId/agents/$agentId/executions/'
    | '/teams/$teamId/projects/$projectId/issues/'
    | '/teams/$teamId/projects/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamsTeamIdRouteRoute: typeof TeamsTeamIdRouteRouteWithChildren
  SettingsAiProvidersRoute: typeof SettingsAiProvidersRoute
  TeamsNewRoute: typeof TeamsNewRoute
  HomeIndexRoute: typeof HomeIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai-providers': {
      id: '/settings/ai-providers'
      path: '/settings/ai-providers'
      fullPath: '/settings/ai-providers'
      preLoaderRoute: typeof SettingsAiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/projects/': {
      id: '/teams/$teamId/projects/'
      path: '/projects'
      fullPath: '/teams/$teamId/projects/'
      preLoaderRoute: typeof TeamsTeamIdProjectsIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/kb/': {
      id: '/teams/$teamId/kb/'
      path: '/kb'
      fullPath: '/teams/$teamId/kb/'
      preLoaderRoute: typeof TeamsTeamIdKbIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/issues/': {
      id: '/teams/$teamId/issues/'
      path: '/issues'
      fullPath: '/teams/$teamId/issues/'
      preLoaderRoute: typeof TeamsTeamIdIssuesIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/inbox/': {
      id: '/teams/$teamId/inbox/'
      path: '/inbox'
      fullPath: '/teams/$teamId/inbox/'
      preLoaderRoute: typeof TeamsTeamIdInboxIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/goals/': {
      id: '/teams/$teamId/goals/'
      path: '/goals'
      fullPath: '/teams/$teamId/goals/'
      preLoaderRoute: typeof TeamsTeamIdGoalsIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/agents/': {
      id: '/teams/$teamId/agents/'
      path: '/agents'
      fullPath: '/teams/$teamId/agents/'
      preLoaderRoute: typeof TeamsTeamIdAgentsIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/settings/general': {
      id: '/teams/$teamId/settings/general'
      path: '/settings/general'
      fullPath: '/teams/$teamId/settings/general'
      preLoaderRoute: typeof TeamsTeamIdSettingsGeneralRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/settings/credentials': {
      id: '/teams/$teamId/settings/credentials'
      path: '/settings/credentials'
      fullPath: '/teams/$teamId/settings/credentials'
      preLoaderRoute: typeof TeamsTeamIdSettingsCredentialsRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/settings/connections': {
      id: '/teams/$teamId/settings/connections'
      path: '/settings/connections'
      fullPath: '/teams/$teamId/settings/connections'
      preLoaderRoute: typeof TeamsTeamIdSettingsConnectionsRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/settings/audit-log': {
      id: '/teams/$teamId/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/teams/$teamId/settings/audit-log'
      preLoaderRoute: typeof TeamsTeamIdSettingsAuditLogRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/issues/$issueId': {
      id: '/teams/$teamId/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/teams/$teamId/issues/$issueId'
      preLoaderRoute: typeof TeamsTeamIdIssuesIssueIdRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/agents/hire': {
      id: '/teams/$teamId/agents/hire'
      path: '/agents/hire'
      fullPath: '/teams/$teamId/agents/hire'
      preLoaderRoute: typeof TeamsTeamIdAgentsHireRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/projects/$projectId': {
      id: '/teams/$teamId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/teams/$teamId/projects/$projectId'
      preLoaderRoute: typeof TeamsTeamIdProjectsProjectIdRouteRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/agents/$agentId': {
      id: '/teams/$teamId/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/teams/$teamId/agents/$agentId'
      preLoaderRoute: typeof TeamsTeamIdAgentsAgentIdRouteRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/projects/$projectId/': {
      id: '/teams/$teamId/projects/$projectId/'
      path: '/'
      fullPath: '/teams/$teamId/projects/$projectId/'
      preLoaderRoute: typeof TeamsTeamIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdProjectsProjectIdRouteRoute
    }
    '/teams/$teamId/agents/$agentId/': {
      id: '/teams/$teamId/agents/$agentId/'
      path: '/'
      fullPath: '/teams/$teamId/agents/$agentId/'
      preLoaderRoute: typeof TeamsTeamIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdAgentsAgentIdRouteRoute
    }
    '/teams/$teamId/projects/$projectId/documents': {
      id: '/teams/$teamId/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/teams/$teamId/projects/$projectId/documents'
      preLoaderRoute: typeof TeamsTeamIdProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof TeamsTeamIdProjectsProjectIdRouteRoute
    }
    '/teams/$teamId/projects/$projectId/container': {
      id: '/teams/$teamId/projects/$projectId/container'
      path: '/container'
      fullPath: '/teams/$teamId/projects/$projectId/container'
      preLoaderRoute: typeof TeamsTeamIdProjectsProjectIdContainerRouteImport
      parentRoute: typeof TeamsTeamIdProjectsProjectIdRouteRoute
    }
    '/teams/$teamId/agents/$agentId/settings': {
      id: '/teams/$teamId/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/teams/$teamId/agents/$agentId/settings'
      preLoaderRoute: typeof TeamsTeamIdAgentsAgentIdSettingsRouteImport
      parentRoute: typeof TeamsTeamIdAgentsAgentIdRouteRoute
    }
    '/teams/$teamId/projects/$projectId/settings/': {
      id: '/teams/$teamId/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/teams/$teamId/projects/$projectId/settings/'
      preLoaderRoute: typeof TeamsTeamIdProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof TeamsTeamIdProjectsProjectIdRouteRoute
    }
    '/teams/$teamId/projects/$projectId/issues/': {
      id: '/teams/$teamId/projects/$projectId/issues/'
      path: '/issues'
      fullPath: '/teams/$teamId/projects/$projectId/issues/'
      preLoaderRoute: typeof TeamsTeamIdProjectsProjectIdIssuesIndexRouteImport
      parentRoute: typeof TeamsTeamIdProjectsProjectIdRouteRoute
    }
    '/teams/$teamId/agents/$agentId/executions/': {
      id: '/teams/$teamId/agents/$agentId/executions/'
      path: '/executions'
      fullPath: '/teams/$teamId/agents/$agentId/executions/'
      preLoaderRoute: typeof TeamsTeamIdAgentsAgentIdExecutionsIndexRouteImport
      parentRoute: typeof TeamsTeamIdAgentsAgentIdRouteRoute
    }
    '/teams/$teamId/projects/$projectId/issues/$issueId': {
      id: '/teams/$teamId/projects/$projectId/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/teams/$teamId/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof TeamsTeamIdProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof TeamsTeamIdProjectsProjectIdRouteRoute
    }
    '/teams/$teamId/agents/$agentId/executions/$runId': {
      id: '/teams/$teamId/agents/$agentId/executions/$runId'
      path: '/executions/$runId'
      fullPath: '/teams/$teamId/agents/$agentId/executions/$runId'
      preLoaderRoute: typeof TeamsTeamIdAgentsAgentIdExecutionsRunIdRouteImport
      parentRoute: typeof TeamsTeamIdAgentsAgentIdRouteRoute
    }
  }
}

interface TeamsTeamIdAgentsAgentIdRouteRouteChildren {
  TeamsTeamIdAgentsAgentIdSettingsRoute: typeof TeamsTeamIdAgentsAgentIdSettingsRoute
  TeamsTeamIdAgentsAgentIdIndexRoute: typeof TeamsTeamIdAgentsAgentIdIndexRoute
  TeamsTeamIdAgentsAgentIdExecutionsRunIdRoute: typeof TeamsTeamIdAgentsAgentIdExecutionsRunIdRoute
  TeamsTeamIdAgentsAgentIdExecutionsIndexRoute: typeof TeamsTeamIdAgentsAgentIdExecutionsIndexRoute
}

const TeamsTeamIdAgentsAgentIdRouteRouteChildren: TeamsTeamIdAgentsAgentIdRouteRouteChildren =
  {
    TeamsTeamIdAgentsAgentIdSettingsRoute:
      TeamsTeamIdAgentsAgentIdSettingsRoute,
    TeamsTeamIdAgentsAgentIdIndexRoute: TeamsTeamIdAgentsAgentIdIndexRoute,
    TeamsTeamIdAgentsAgentIdExecutionsRunIdRoute:
      TeamsTeamIdAgentsAgentIdExecutionsRunIdRoute,
    TeamsTeamIdAgentsAgentIdExecutionsIndexRoute:
      TeamsTeamIdAgentsAgentIdExecutionsIndexRoute,
  }

const TeamsTeamIdAgentsAgentIdRouteRouteWithChildren =
  TeamsTeamIdAgentsAgentIdRouteRoute._addFileChildren(
    TeamsTeamIdAgentsAgentIdRouteRouteChildren,
  )

interface TeamsTeamIdProjectsProjectIdRouteRouteChildren {
  TeamsTeamIdProjectsProjectIdContainerRoute: typeof TeamsTeamIdProjectsProjectIdContainerRoute
  TeamsTeamIdProjectsProjectIdDocumentsRoute: typeof TeamsTeamIdProjectsProjectIdDocumentsRoute
  TeamsTeamIdProjectsProjectIdIndexRoute: typeof TeamsTeamIdProjectsProjectIdIndexRoute
  TeamsTeamIdProjectsProjectIdIssuesIssueIdRoute: typeof TeamsTeamIdProjectsProjectIdIssuesIssueIdRoute
  TeamsTeamIdProjectsProjectIdIssuesIndexRoute: typeof TeamsTeamIdProjectsProjectIdIssuesIndexRoute
  TeamsTeamIdProjectsProjectIdSettingsIndexRoute: typeof TeamsTeamIdProjectsProjectIdSettingsIndexRoute
}

const TeamsTeamIdProjectsProjectIdRouteRouteChildren: TeamsTeamIdProjectsProjectIdRouteRouteChildren =
  {
    TeamsTeamIdProjectsProjectIdContainerRoute:
      TeamsTeamIdProjectsProjectIdContainerRoute,
    TeamsTeamIdProjectsProjectIdDocumentsRoute:
      TeamsTeamIdProjectsProjectIdDocumentsRoute,
    TeamsTeamIdProjectsProjectIdIndexRoute:
      TeamsTeamIdProjectsProjectIdIndexRoute,
    TeamsTeamIdProjectsProjectIdIssuesIssueIdRoute:
      TeamsTeamIdProjectsProjectIdIssuesIssueIdRoute,
    TeamsTeamIdProjectsProjectIdIssuesIndexRoute:
      TeamsTeamIdProjectsProjectIdIssuesIndexRoute,
    TeamsTeamIdProjectsProjectIdSettingsIndexRoute:
      TeamsTeamIdProjectsProjectIdSettingsIndexRoute,
  }

const TeamsTeamIdProjectsProjectIdRouteRouteWithChildren =
  TeamsTeamIdProjectsProjectIdRouteRoute._addFileChildren(
    TeamsTeamIdProjectsProjectIdRouteRouteChildren,
  )

interface TeamsTeamIdRouteRouteChildren {
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  TeamsTeamIdAgentsAgentIdRouteRoute: typeof TeamsTeamIdAgentsAgentIdRouteRouteWithChildren
  TeamsTeamIdProjectsProjectIdRouteRoute: typeof TeamsTeamIdProjectsProjectIdRouteRouteWithChildren
  TeamsTeamIdAgentsHireRoute: typeof TeamsTeamIdAgentsHireRoute
  TeamsTeamIdIssuesIssueIdRoute: typeof TeamsTeamIdIssuesIssueIdRoute
  TeamsTeamIdSettingsAuditLogRoute: typeof TeamsTeamIdSettingsAuditLogRoute
  TeamsTeamIdSettingsConnectionsRoute: typeof TeamsTeamIdSettingsConnectionsRoute
  TeamsTeamIdSettingsCredentialsRoute: typeof TeamsTeamIdSettingsCredentialsRoute
  TeamsTeamIdSettingsGeneralRoute: typeof TeamsTeamIdSettingsGeneralRoute
  TeamsTeamIdAgentsIndexRoute: typeof TeamsTeamIdAgentsIndexRoute
  TeamsTeamIdGoalsIndexRoute: typeof TeamsTeamIdGoalsIndexRoute
  TeamsTeamIdInboxIndexRoute: typeof TeamsTeamIdInboxIndexRoute
  TeamsTeamIdIssuesIndexRoute: typeof TeamsTeamIdIssuesIndexRoute
  TeamsTeamIdKbIndexRoute: typeof TeamsTeamIdKbIndexRoute
  TeamsTeamIdProjectsIndexRoute: typeof TeamsTeamIdProjectsIndexRoute
}

const TeamsTeamIdRouteRouteChildren: TeamsTeamIdRouteRouteChildren = {
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  TeamsTeamIdAgentsAgentIdRouteRoute:
    TeamsTeamIdAgentsAgentIdRouteRouteWithChildren,
  TeamsTeamIdProjectsProjectIdRouteRoute:
    TeamsTeamIdProjectsProjectIdRouteRouteWithChildren,
  TeamsTeamIdAgentsHireRoute: TeamsTeamIdAgentsHireRoute,
  TeamsTeamIdIssuesIssueIdRoute: TeamsTeamIdIssuesIssueIdRoute,
  TeamsTeamIdSettingsAuditLogRoute: TeamsTeamIdSettingsAuditLogRoute,
  TeamsTeamIdSettingsConnectionsRoute: TeamsTeamIdSettingsConnectionsRoute,
  TeamsTeamIdSettingsCredentialsRoute: TeamsTeamIdSettingsCredentialsRoute,
  TeamsTeamIdSettingsGeneralRoute: TeamsTeamIdSettingsGeneralRoute,
  TeamsTeamIdAgentsIndexRoute: TeamsTeamIdAgentsIndexRoute,
  TeamsTeamIdGoalsIndexRoute: TeamsTeamIdGoalsIndexRoute,
  TeamsTeamIdInboxIndexRoute: TeamsTeamIdInboxIndexRoute,
  TeamsTeamIdIssuesIndexRoute: TeamsTeamIdIssuesIndexRoute,
  TeamsTeamIdKbIndexRoute: TeamsTeamIdKbIndexRoute,
  TeamsTeamIdProjectsIndexRoute: TeamsTeamIdProjectsIndexRoute,
}

const TeamsTeamIdRouteRouteWithChildren =
  TeamsTeamIdRouteRoute._addFileChildren(TeamsTeamIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamsTeamIdRouteRoute: TeamsTeamIdRouteRouteWithChildren,
  SettingsAiProvidersRoute: SettingsAiProvidersRoute,
  TeamsNewRoute: TeamsNewRoute,
  HomeIndexRoute: HomeIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
