/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as SettingsSkillsRouteImport } from './routes/settings/skills'
import { Route as SettingsCredentialsRouteImport } from './routes/settings/credentials'
import { Route as SettingsConnectorsRouteImport } from './routes/settings/connectors'
import { Route as SettingsChatboxRouteImport } from './routes/settings/chatbox'
import { Route as SettingsAuditLogRouteImport } from './routes/settings/audit-log'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsAiProvidersRouteImport } from './routes/settings/ai-providers'
import { Route as SettingsAdminPasswordRouteImport } from './routes/settings/admin-password'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as HomeInboxIndexRouteImport } from './routes/home/inbox/index'
import { Route as ProjectsProjectIdSkillsRouteImport } from './routes/projects/$projectId/skills'
import { Route as ProjectsProjectIdGitRouteImport } from './routes/projects/$projectId/git'
import { Route as ProjectsProjectIdDocumentsRouteImport } from './routes/projects/$projectId/documents'
import { Route as ProjectsProjectIdContainerRouteImport } from './routes/projects/$projectId/container'
import { Route as ProjectsProjectIdConnectorsRouteImport } from './routes/projects/$projectId/connectors'
import { Route as ProjectsProjectIdBudgetRouteImport } from './routes/projects/$projectId/budget'
import { Route as ProjectsProjectIdAuditLogRouteImport } from './routes/projects/$projectId/audit-log'
import { Route as ProjectsProjectIdAssetsRouteImport } from './routes/projects/$projectId/assets'
import { Route as PreviewProjectIdFilenameRouteImport } from './routes/preview/$projectId/$filename'
import { Route as ProjectsProjectIdTasksIndexRouteImport } from './routes/projects/$projectId/tasks/index'
import { Route as ProjectsProjectIdSettingsIndexRouteImport } from './routes/projects/$projectId/settings/index'
import { Route as ProjectsProjectIdInboxIndexRouteImport } from './routes/projects/$projectId/inbox/index'
import { Route as ProjectsProjectIdGoalsIndexRouteImport } from './routes/projects/$projectId/goals/index'
import { Route as ProjectsProjectIdAgentsIndexRouteImport } from './routes/projects/$projectId/agents/index'
import { Route as ProjectsProjectIdTeamSettingsGeneralRouteImport } from './routes/projects/$projectId/team-settings/general'
import { Route as ProjectsProjectIdTasksTaskIdRouteImport } from './routes/projects/$projectId/tasks/$taskId'
import { Route as ProjectsProjectIdGoalsGoalIdRouteImport } from './routes/projects/$projectId/goals/$goalId'
import { Route as ProjectsProjectIdAssetsViewRouteImport } from './routes/projects/$projectId/assets_.view'
import { Route as ProjectsProjectIdAgentsHireRouteImport } from './routes/projects/$projectId/agents/hire'
import { Route as ProjectsProjectIdAgentsAgentIdRouteRouteImport } from './routes/projects/$projectId/agents/$agentId/route'
import { Route as ProjectsProjectIdAgentsAgentIdIndexRouteImport } from './routes/projects/$projectId/agents/$agentId/index'
import { Route as ProjectsProjectIdAgentsAgentIdSettingsRouteImport } from './routes/projects/$projectId/agents/$agentId/settings'
import { Route as ProjectsProjectIdAgentsAgentIdChatHistoryRouteImport } from './routes/projects/$projectId/agents/$agentId/chat-history'
import { Route as ProjectsProjectIdAgentsAgentIdExecutionsIndexRouteImport } from './routes/projects/$projectId/agents/$agentId/executions/index'
import { Route as ProjectsProjectIdAgentsAgentIdExecutionsRunIdRouteImport } from './routes/projects/$projectId/agents/$agentId/executions/$runId'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCredentialsRoute = SettingsCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsConnectorsRoute = SettingsConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsChatboxRoute = SettingsChatboxRouteImport.update({
  id: '/chatbox',
  path: '/chatbox',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAiProvidersRoute = SettingsAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAdminPasswordRoute = SettingsAdminPasswordRouteImport.update({
  id: '/admin-password',
  path: '/admin-password',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const HomeInboxIndexRoute = HomeInboxIndexRouteImport.update({
  id: '/home/inbox/',
  path: '/home/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSkillsRoute = ProjectsProjectIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdGitRoute = ProjectsProjectIdGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdDocumentsRoute =
  ProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdContainerRoute =
  ProjectsProjectIdContainerRouteImport.update({
    id: '/container',
    path: '/container',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdConnectorsRoute =
  ProjectsProjectIdConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdBudgetRoute = ProjectsProjectIdBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdAuditLogRoute =
  ProjectsProjectIdAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdAssetsRoute = ProjectsProjectIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const PreviewProjectIdFilenameRoute =
  PreviewProjectIdFilenameRouteImport.update({
    id: '/preview/$projectId/$filename',
    path: '/preview/$projectId/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdTasksIndexRoute =
  ProjectsProjectIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdSettingsIndexRoute =
  ProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdInboxIndexRoute =
  ProjectsProjectIdInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdGoalsIndexRoute =
  ProjectsProjectIdGoalsIndexRouteImport.update({
    id: '/goals/',
    path: '/goals/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsIndexRoute =
  ProjectsProjectIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdTeamSettingsGeneralRoute =
  ProjectsProjectIdTeamSettingsGeneralRouteImport.update({
    id: '/team-settings/general',
    path: '/team-settings/general',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdTasksTaskIdRoute =
  ProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdGoalsGoalIdRoute =
  ProjectsProjectIdGoalsGoalIdRouteImport.update({
    id: '/goals/$goalId',
    path: '/goals/$goalId',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdAssetsViewRoute =
  ProjectsProjectIdAssetsViewRouteImport.update({
    id: '/assets_/view',
    path: '/assets/view',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsHireRoute =
  ProjectsProjectIdAgentsHireRouteImport.update({
    id: '/agents/hire',
    path: '/agents/hire',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsAgentIdRouteRoute =
  ProjectsProjectIdAgentsAgentIdRouteRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsAgentIdIndexRoute =
  ProjectsProjectIdAgentsAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdAgentsAgentIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsAgentIdSettingsRoute =
  ProjectsProjectIdAgentsAgentIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdAgentsAgentIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsAgentIdChatHistoryRoute =
  ProjectsProjectIdAgentsAgentIdChatHistoryRouteImport.update({
    id: '/chat-history',
    path: '/chat-history',
    getParentRoute: () => ProjectsProjectIdAgentsAgentIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsAgentIdExecutionsIndexRoute =
  ProjectsProjectIdAgentsAgentIdExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => ProjectsProjectIdAgentsAgentIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsAgentIdExecutionsRunIdRoute =
  ProjectsProjectIdAgentsAgentIdExecutionsRunIdRouteImport.update({
    id: '/executions/$runId',
    path: '/executions/$runId',
    getParentRoute: () => ProjectsProjectIdAgentsAgentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/settings/admin-password': typeof SettingsAdminPasswordRoute
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/chatbox': typeof SettingsChatboxRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/credentials': typeof SettingsCredentialsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/home/': typeof HomeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/preview/$projectId/$filename': typeof PreviewProjectIdFilenameRoute
  '/projects/$projectId/assets': typeof ProjectsProjectIdAssetsRoute
  '/projects/$projectId/audit-log': typeof ProjectsProjectIdAuditLogRoute
  '/projects/$projectId/budget': typeof ProjectsProjectIdBudgetRoute
  '/projects/$projectId/connectors': typeof ProjectsProjectIdConnectorsRoute
  '/projects/$projectId/container': typeof ProjectsProjectIdContainerRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/git': typeof ProjectsProjectIdGitRoute
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsRoute
  '/home/inbox/': typeof HomeInboxIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/agents/$agentId': typeof ProjectsProjectIdAgentsAgentIdRouteRouteWithChildren
  '/projects/$projectId/agents/hire': typeof ProjectsProjectIdAgentsHireRoute
  '/projects/$projectId/assets/view': typeof ProjectsProjectIdAssetsViewRoute
  '/projects/$projectId/goals/$goalId': typeof ProjectsProjectIdGoalsGoalIdRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/team-settings/general': typeof ProjectsProjectIdTeamSettingsGeneralRoute
  '/projects/$projectId/agents/': typeof ProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/goals/': typeof ProjectsProjectIdGoalsIndexRoute
  '/projects/$projectId/inbox/': typeof ProjectsProjectIdInboxIndexRoute
  '/projects/$projectId/settings/': typeof ProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/tasks/': typeof ProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/agents/$agentId/chat-history': typeof ProjectsProjectIdAgentsAgentIdChatHistoryRoute
  '/projects/$projectId/agents/$agentId/settings': typeof ProjectsProjectIdAgentsAgentIdSettingsRoute
  '/projects/$projectId/agents/$agentId/': typeof ProjectsProjectIdAgentsAgentIdIndexRoute
  '/projects/$projectId/agents/$agentId/executions/$runId': typeof ProjectsProjectIdAgentsAgentIdExecutionsRunIdRoute
  '/projects/$projectId/agents/$agentId/executions/': typeof ProjectsProjectIdAgentsAgentIdExecutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/admin-password': typeof SettingsAdminPasswordRoute
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/chatbox': typeof SettingsChatboxRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/credentials': typeof SettingsCredentialsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/home': typeof HomeIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/preview/$projectId/$filename': typeof PreviewProjectIdFilenameRoute
  '/projects/$projectId/assets': typeof ProjectsProjectIdAssetsRoute
  '/projects/$projectId/audit-log': typeof ProjectsProjectIdAuditLogRoute
  '/projects/$projectId/budget': typeof ProjectsProjectIdBudgetRoute
  '/projects/$projectId/connectors': typeof ProjectsProjectIdConnectorsRoute
  '/projects/$projectId/container': typeof ProjectsProjectIdContainerRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/git': typeof ProjectsProjectIdGitRoute
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsRoute
  '/home/inbox': typeof HomeInboxIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/agents/hire': typeof ProjectsProjectIdAgentsHireRoute
  '/projects/$projectId/assets/view': typeof ProjectsProjectIdAssetsViewRoute
  '/projects/$projectId/goals/$goalId': typeof ProjectsProjectIdGoalsGoalIdRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/team-settings/general': typeof ProjectsProjectIdTeamSettingsGeneralRoute
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/goals': typeof ProjectsProjectIdGoalsIndexRoute
  '/projects/$projectId/inbox': typeof ProjectsProjectIdInboxIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/agents/$agentId/chat-history': typeof ProjectsProjectIdAgentsAgentIdChatHistoryRoute
  '/projects/$projectId/agents/$agentId/settings': typeof ProjectsProjectIdAgentsAgentIdSettingsRoute
  '/projects/$projectId/agents/$agentId': typeof ProjectsProjectIdAgentsAgentIdIndexRoute
  '/projects/$projectId/agents/$agentId/executions/$runId': typeof ProjectsProjectIdAgentsAgentIdExecutionsRunIdRoute
  '/projects/$projectId/agents/$agentId/executions': typeof ProjectsProjectIdAgentsAgentIdExecutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/settings/admin-password': typeof SettingsAdminPasswordRoute
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/chatbox': typeof SettingsChatboxRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/credentials': typeof SettingsCredentialsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/home/': typeof HomeIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/preview/$projectId/$filename': typeof PreviewProjectIdFilenameRoute
  '/projects/$projectId/assets': typeof ProjectsProjectIdAssetsRoute
  '/projects/$projectId/audit-log': typeof ProjectsProjectIdAuditLogRoute
  '/projects/$projectId/budget': typeof ProjectsProjectIdBudgetRoute
  '/projects/$projectId/connectors': typeof ProjectsProjectIdConnectorsRoute
  '/projects/$projectId/container': typeof ProjectsProjectIdContainerRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/git': typeof ProjectsProjectIdGitRoute
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsRoute
  '/home/inbox/': typeof HomeInboxIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/agents/$agentId': typeof ProjectsProjectIdAgentsAgentIdRouteRouteWithChildren
  '/projects/$projectId/agents/hire': typeof ProjectsProjectIdAgentsHireRoute
  '/projects/$projectId/assets_/view': typeof ProjectsProjectIdAssetsViewRoute
  '/projects/$projectId/goals/$goalId': typeof ProjectsProjectIdGoalsGoalIdRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/team-settings/general': typeof ProjectsProjectIdTeamSettingsGeneralRoute
  '/projects/$projectId/agents/': typeof ProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/goals/': typeof ProjectsProjectIdGoalsIndexRoute
  '/projects/$projectId/inbox/': typeof ProjectsProjectIdInboxIndexRoute
  '/projects/$projectId/settings/': typeof ProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/tasks/': typeof ProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/agents/$agentId/chat-history': typeof ProjectsProjectIdAgentsAgentIdChatHistoryRoute
  '/projects/$projectId/agents/$agentId/settings': typeof ProjectsProjectIdAgentsAgentIdSettingsRoute
  '/projects/$projectId/agents/$agentId/': typeof ProjectsProjectIdAgentsAgentIdIndexRoute
  '/projects/$projectId/agents/$agentId/executions/$runId': typeof ProjectsProjectIdAgentsAgentIdExecutionsRunIdRoute
  '/projects/$projectId/agents/$agentId/executions/': typeof ProjectsProjectIdAgentsAgentIdExecutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/projects/$projectId'
    | '/settings/admin-password'
    | '/settings/ai-providers'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/chatbox'
    | '/settings/connectors'
    | '/settings/credentials'
    | '/settings/skills'
    | '/home/'
    | '/settings/'
    | '/preview/$projectId/$filename'
    | '/projects/$projectId/assets'
    | '/projects/$projectId/audit-log'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/connectors'
    | '/projects/$projectId/container'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/git'
    | '/projects/$projectId/skills'
    | '/home/inbox/'
    | '/projects/$projectId/'
    | '/projects/$projectId/agents/$agentId'
    | '/projects/$projectId/agents/hire'
    | '/projects/$projectId/assets/view'
    | '/projects/$projectId/goals/$goalId'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/team-settings/general'
    | '/projects/$projectId/agents/'
    | '/projects/$projectId/goals/'
    | '/projects/$projectId/inbox/'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/tasks/'
    | '/projects/$projectId/agents/$agentId/chat-history'
    | '/projects/$projectId/agents/$agentId/settings'
    | '/projects/$projectId/agents/$agentId/'
    | '/projects/$projectId/agents/$agentId/executions/$runId'
    | '/projects/$projectId/agents/$agentId/executions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/admin-password'
    | '/settings/ai-providers'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/chatbox'
    | '/settings/connectors'
    | '/settings/credentials'
    | '/settings/skills'
    | '/home'
    | '/settings'
    | '/preview/$projectId/$filename'
    | '/projects/$projectId/assets'
    | '/projects/$projectId/audit-log'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/connectors'
    | '/projects/$projectId/container'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/git'
    | '/projects/$projectId/skills'
    | '/home/inbox'
    | '/projects/$projectId'
    | '/projects/$projectId/agents/hire'
    | '/projects/$projectId/assets/view'
    | '/projects/$projectId/goals/$goalId'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/team-settings/general'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/goals'
    | '/projects/$projectId/inbox'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/agents/$agentId/chat-history'
    | '/projects/$projectId/agents/$agentId/settings'
    | '/projects/$projectId/agents/$agentId'
    | '/projects/$projectId/agents/$agentId/executions/$runId'
    | '/projects/$projectId/agents/$agentId/executions'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/projects/$projectId'
    | '/settings/admin-password'
    | '/settings/ai-providers'
    | '/settings/api-keys'
    | '/settings/audit-log'
    | '/settings/chatbox'
    | '/settings/connectors'
    | '/settings/credentials'
    | '/settings/skills'
    | '/home/'
    | '/settings/'
    | '/preview/$projectId/$filename'
    | '/projects/$projectId/assets'
    | '/projects/$projectId/audit-log'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/connectors'
    | '/projects/$projectId/container'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/git'
    | '/projects/$projectId/skills'
    | '/home/inbox/'
    | '/projects/$projectId/'
    | '/projects/$projectId/agents/$agentId'
    | '/projects/$projectId/agents/hire'
    | '/projects/$projectId/assets_/view'
    | '/projects/$projectId/goals/$goalId'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/team-settings/general'
    | '/projects/$projectId/agents/'
    | '/projects/$projectId/goals/'
    | '/projects/$projectId/inbox/'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/tasks/'
    | '/projects/$projectId/agents/$agentId/chat-history'
    | '/projects/$projectId/agents/$agentId/settings'
    | '/projects/$projectId/agents/$agentId/'
    | '/projects/$projectId/agents/$agentId/executions/$runId'
    | '/projects/$projectId/agents/$agentId/executions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
  PreviewProjectIdFilenameRoute: typeof PreviewProjectIdFilenameRoute
  HomeInboxIndexRoute: typeof HomeInboxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/credentials': {
      id: '/settings/credentials'
      path: '/credentials'
      fullPath: '/settings/credentials'
      preLoaderRoute: typeof SettingsCredentialsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/connectors': {
      id: '/settings/connectors'
      path: '/connectors'
      fullPath: '/settings/connectors'
      preLoaderRoute: typeof SettingsConnectorsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/chatbox': {
      id: '/settings/chatbox'
      path: '/chatbox'
      fullPath: '/settings/chatbox'
      preLoaderRoute: typeof SettingsChatboxRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/audit-log': {
      id: '/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/ai-providers': {
      id: '/settings/ai-providers'
      path: '/ai-providers'
      fullPath: '/settings/ai-providers'
      preLoaderRoute: typeof SettingsAiProvidersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/admin-password': {
      id: '/settings/admin-password'
      path: '/admin-password'
      fullPath: '/settings/admin-password'
      preLoaderRoute: typeof SettingsAdminPasswordRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/home/inbox/': {
      id: '/home/inbox/'
      path: '/home/inbox'
      fullPath: '/home/inbox/'
      preLoaderRoute: typeof HomeInboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/skills': {
      id: '/projects/$projectId/skills'
      path: '/skills'
      fullPath: '/projects/$projectId/skills'
      preLoaderRoute: typeof ProjectsProjectIdSkillsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/git': {
      id: '/projects/$projectId/git'
      path: '/git'
      fullPath: '/projects/$projectId/git'
      preLoaderRoute: typeof ProjectsProjectIdGitRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/container': {
      id: '/projects/$projectId/container'
      path: '/container'
      fullPath: '/projects/$projectId/container'
      preLoaderRoute: typeof ProjectsProjectIdContainerRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/connectors': {
      id: '/projects/$projectId/connectors'
      path: '/connectors'
      fullPath: '/projects/$projectId/connectors'
      preLoaderRoute: typeof ProjectsProjectIdConnectorsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/budget': {
      id: '/projects/$projectId/budget'
      path: '/budget'
      fullPath: '/projects/$projectId/budget'
      preLoaderRoute: typeof ProjectsProjectIdBudgetRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/audit-log': {
      id: '/projects/$projectId/audit-log'
      path: '/audit-log'
      fullPath: '/projects/$projectId/audit-log'
      preLoaderRoute: typeof ProjectsProjectIdAuditLogRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/assets': {
      id: '/projects/$projectId/assets'
      path: '/assets'
      fullPath: '/projects/$projectId/assets'
      preLoaderRoute: typeof ProjectsProjectIdAssetsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/preview/$projectId/$filename': {
      id: '/preview/$projectId/$filename'
      path: '/preview/$projectId/$filename'
      fullPath: '/preview/$projectId/$filename'
      preLoaderRoute: typeof PreviewProjectIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/tasks/': {
      id: '/projects/$projectId/tasks/'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks/'
      preLoaderRoute: typeof ProjectsProjectIdTasksIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/settings/': {
      id: '/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof ProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/inbox/': {
      id: '/projects/$projectId/inbox/'
      path: '/inbox'
      fullPath: '/projects/$projectId/inbox/'
      preLoaderRoute: typeof ProjectsProjectIdInboxIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/goals/': {
      id: '/projects/$projectId/goals/'
      path: '/goals'
      fullPath: '/projects/$projectId/goals/'
      preLoaderRoute: typeof ProjectsProjectIdGoalsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/agents/': {
      id: '/projects/$projectId/agents/'
      path: '/agents'
      fullPath: '/projects/$projectId/agents/'
      preLoaderRoute: typeof ProjectsProjectIdAgentsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/team-settings/general': {
      id: '/projects/$projectId/team-settings/general'
      path: '/team-settings/general'
      fullPath: '/projects/$projectId/team-settings/general'
      preLoaderRoute: typeof ProjectsProjectIdTeamSettingsGeneralRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/tasks/$taskId': {
      id: '/projects/$projectId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof ProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/goals/$goalId': {
      id: '/projects/$projectId/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/projects/$projectId/goals/$goalId'
      preLoaderRoute: typeof ProjectsProjectIdGoalsGoalIdRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/assets_/view': {
      id: '/projects/$projectId/assets_/view'
      path: '/assets/view'
      fullPath: '/projects/$projectId/assets/view'
      preLoaderRoute: typeof ProjectsProjectIdAssetsViewRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/agents/hire': {
      id: '/projects/$projectId/agents/hire'
      path: '/agents/hire'
      fullPath: '/projects/$projectId/agents/hire'
      preLoaderRoute: typeof ProjectsProjectIdAgentsHireRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/agents/$agentId': {
      id: '/projects/$projectId/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/projects/$projectId/agents/$agentId'
      preLoaderRoute: typeof ProjectsProjectIdAgentsAgentIdRouteRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/agents/$agentId/': {
      id: '/projects/$projectId/agents/$agentId/'
      path: '/'
      fullPath: '/projects/$projectId/agents/$agentId/'
      preLoaderRoute: typeof ProjectsProjectIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdAgentsAgentIdRouteRoute
    }
    '/projects/$projectId/agents/$agentId/settings': {
      id: '/projects/$projectId/agents/$agentId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/agents/$agentId/settings'
      preLoaderRoute: typeof ProjectsProjectIdAgentsAgentIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdAgentsAgentIdRouteRoute
    }
    '/projects/$projectId/agents/$agentId/chat-history': {
      id: '/projects/$projectId/agents/$agentId/chat-history'
      path: '/chat-history'
      fullPath: '/projects/$projectId/agents/$agentId/chat-history'
      preLoaderRoute: typeof ProjectsProjectIdAgentsAgentIdChatHistoryRouteImport
      parentRoute: typeof ProjectsProjectIdAgentsAgentIdRouteRoute
    }
    '/projects/$projectId/agents/$agentId/executions/': {
      id: '/projects/$projectId/agents/$agentId/executions/'
      path: '/executions'
      fullPath: '/projects/$projectId/agents/$agentId/executions/'
      preLoaderRoute: typeof ProjectsProjectIdAgentsAgentIdExecutionsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdAgentsAgentIdRouteRoute
    }
    '/projects/$projectId/agents/$agentId/executions/$runId': {
      id: '/projects/$projectId/agents/$agentId/executions/$runId'
      path: '/executions/$runId'
      fullPath: '/projects/$projectId/agents/$agentId/executions/$runId'
      preLoaderRoute: typeof ProjectsProjectIdAgentsAgentIdExecutionsRunIdRouteImport
      parentRoute: typeof ProjectsProjectIdAgentsAgentIdRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAdminPasswordRoute: typeof SettingsAdminPasswordRoute
  SettingsAiProvidersRoute: typeof SettingsAiProvidersRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  SettingsChatboxRoute: typeof SettingsChatboxRoute
  SettingsConnectorsRoute: typeof SettingsConnectorsRoute
  SettingsCredentialsRoute: typeof SettingsCredentialsRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAdminPasswordRoute: SettingsAdminPasswordRoute,
  SettingsAiProvidersRoute: SettingsAiProvidersRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  SettingsChatboxRoute: SettingsChatboxRoute,
  SettingsConnectorsRoute: SettingsConnectorsRoute,
  SettingsCredentialsRoute: SettingsCredentialsRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ProjectsProjectIdAgentsAgentIdRouteRouteChildren {
  ProjectsProjectIdAgentsAgentIdChatHistoryRoute: typeof ProjectsProjectIdAgentsAgentIdChatHistoryRoute
  ProjectsProjectIdAgentsAgentIdSettingsRoute: typeof ProjectsProjectIdAgentsAgentIdSettingsRoute
  ProjectsProjectIdAgentsAgentIdIndexRoute: typeof ProjectsProjectIdAgentsAgentIdIndexRoute
  ProjectsProjectIdAgentsAgentIdExecutionsRunIdRoute: typeof ProjectsProjectIdAgentsAgentIdExecutionsRunIdRoute
  ProjectsProjectIdAgentsAgentIdExecutionsIndexRoute: typeof ProjectsProjectIdAgentsAgentIdExecutionsIndexRoute
}

const ProjectsProjectIdAgentsAgentIdRouteRouteChildren: ProjectsProjectIdAgentsAgentIdRouteRouteChildren =
  {
    ProjectsProjectIdAgentsAgentIdChatHistoryRoute:
      ProjectsProjectIdAgentsAgentIdChatHistoryRoute,
    ProjectsProjectIdAgentsAgentIdSettingsRoute:
      ProjectsProjectIdAgentsAgentIdSettingsRoute,
    ProjectsProjectIdAgentsAgentIdIndexRoute:
      ProjectsProjectIdAgentsAgentIdIndexRoute,
    ProjectsProjectIdAgentsAgentIdExecutionsRunIdRoute:
      ProjectsProjectIdAgentsAgentIdExecutionsRunIdRoute,
    ProjectsProjectIdAgentsAgentIdExecutionsIndexRoute:
      ProjectsProjectIdAgentsAgentIdExecutionsIndexRoute,
  }

const ProjectsProjectIdAgentsAgentIdRouteRouteWithChildren =
  ProjectsProjectIdAgentsAgentIdRouteRoute._addFileChildren(
    ProjectsProjectIdAgentsAgentIdRouteRouteChildren,
  )

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdAssetsRoute: typeof ProjectsProjectIdAssetsRoute
  ProjectsProjectIdAuditLogRoute: typeof ProjectsProjectIdAuditLogRoute
  ProjectsProjectIdBudgetRoute: typeof ProjectsProjectIdBudgetRoute
  ProjectsProjectIdConnectorsRoute: typeof ProjectsProjectIdConnectorsRoute
  ProjectsProjectIdContainerRoute: typeof ProjectsProjectIdContainerRoute
  ProjectsProjectIdDocumentsRoute: typeof ProjectsProjectIdDocumentsRoute
  ProjectsProjectIdGitRoute: typeof ProjectsProjectIdGitRoute
  ProjectsProjectIdSkillsRoute: typeof ProjectsProjectIdSkillsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdAgentsAgentIdRouteRoute: typeof ProjectsProjectIdAgentsAgentIdRouteRouteWithChildren
  ProjectsProjectIdAgentsHireRoute: typeof ProjectsProjectIdAgentsHireRoute
  ProjectsProjectIdAssetsViewRoute: typeof ProjectsProjectIdAssetsViewRoute
  ProjectsProjectIdGoalsGoalIdRoute: typeof ProjectsProjectIdGoalsGoalIdRoute
  ProjectsProjectIdTasksTaskIdRoute: typeof ProjectsProjectIdTasksTaskIdRoute
  ProjectsProjectIdTeamSettingsGeneralRoute: typeof ProjectsProjectIdTeamSettingsGeneralRoute
  ProjectsProjectIdAgentsIndexRoute: typeof ProjectsProjectIdAgentsIndexRoute
  ProjectsProjectIdGoalsIndexRoute: typeof ProjectsProjectIdGoalsIndexRoute
  ProjectsProjectIdInboxIndexRoute: typeof ProjectsProjectIdInboxIndexRoute
  ProjectsProjectIdSettingsIndexRoute: typeof ProjectsProjectIdSettingsIndexRoute
  ProjectsProjectIdTasksIndexRoute: typeof ProjectsProjectIdTasksIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdAssetsRoute: ProjectsProjectIdAssetsRoute,
    ProjectsProjectIdAuditLogRoute: ProjectsProjectIdAuditLogRoute,
    ProjectsProjectIdBudgetRoute: ProjectsProjectIdBudgetRoute,
    ProjectsProjectIdConnectorsRoute: ProjectsProjectIdConnectorsRoute,
    ProjectsProjectIdContainerRoute: ProjectsProjectIdContainerRoute,
    ProjectsProjectIdDocumentsRoute: ProjectsProjectIdDocumentsRoute,
    ProjectsProjectIdGitRoute: ProjectsProjectIdGitRoute,
    ProjectsProjectIdSkillsRoute: ProjectsProjectIdSkillsRoute,
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
    ProjectsProjectIdAgentsAgentIdRouteRoute:
      ProjectsProjectIdAgentsAgentIdRouteRouteWithChildren,
    ProjectsProjectIdAgentsHireRoute: ProjectsProjectIdAgentsHireRoute,
    ProjectsProjectIdAssetsViewRoute: ProjectsProjectIdAssetsViewRoute,
    ProjectsProjectIdGoalsGoalIdRoute: ProjectsProjectIdGoalsGoalIdRoute,
    ProjectsProjectIdTasksTaskIdRoute: ProjectsProjectIdTasksTaskIdRoute,
    ProjectsProjectIdTeamSettingsGeneralRoute:
      ProjectsProjectIdTeamSettingsGeneralRoute,
    ProjectsProjectIdAgentsIndexRoute: ProjectsProjectIdAgentsIndexRoute,
    ProjectsProjectIdGoalsIndexRoute: ProjectsProjectIdGoalsIndexRoute,
    ProjectsProjectIdInboxIndexRoute: ProjectsProjectIdInboxIndexRoute,
    ProjectsProjectIdSettingsIndexRoute: ProjectsProjectIdSettingsIndexRoute,
    ProjectsProjectIdTasksIndexRoute: ProjectsProjectIdTasksIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
  PreviewProjectIdFilenameRoute: PreviewProjectIdFilenameRoute,
  HomeInboxIndexRoute: HomeInboxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
