import { expect, test } from './fixtures';

test.describe('agent team relationships section', () => {
	for (const viewport of [
		{ name: 'mobile', width: 375, height: 800 },
		{ name: 'tablet', width: 800, height: 1024 },
		{ name: 'desktop', width: 1280, height: 800 },
	]) {
		test(`renders default team_context for an Engineer (${viewport.name})`, async ({
			page,
			freshWorkspace,
		}) => {
			await page.setViewportSize({ width: viewport.width, height: viewport.height });
			const { team, agents } = freshWorkspace;
			const engineer = agents.find((a) => a.slug === 'engineer');
			if (!engineer) throw new Error('engineer agent missing from fresh workspace');

			await page.goto(`/teams/${team.slug}/agents/${engineer.id}/settings`);

			const section = page.getByTestId('agent-team-context');
			await expect(section).toBeVisible({ timeout: 20000 });
			await expect(section).toContainText('@architect');
		});
	}

	test('attribution caption renders beneath the section', async ({ page, freshWorkspace }) => {
		const { team, agents } = freshWorkspace;
		const agent = agents.find((a) => a.slug === 'engineer') ?? agents[0];

		await page.goto(`/teams/${team.slug}/agents/${agent.id}/settings`);

		const caption = page.getByTestId('agent-team-context-attribution');
		await expect(caption).toBeVisible({ timeout: 20000 });
		await expect(caption).toContainText('Auto-generated by the Captain');
	});

	test('section appears between Reports To and Monthly Budget controls', async ({
		page,
		freshWorkspace,
	}) => {
		const { team, agents } = freshWorkspace;
		const agent = agents.find((a) => a.slug === 'engineer') ?? agents[0];

		await page.goto(`/teams/${team.slug}/agents/${agent.id}/settings`);

		const section = page.getByTestId('agent-team-context');
		await expect(section).toBeVisible({ timeout: 20000 });

		const reportsToLabel = page.getByText('Reports To').first();
		const budgetLabel = page.getByText('Monthly Budget').first();
		await expect(reportsToLabel).toBeVisible();
		await expect(budgetLabel).toBeVisible();

		const reportsBox = await reportsToLabel.boundingBox();
		const sectionBox = await section.boundingBox();
		const budgetBox = await budgetLabel.boundingBox();
		if (!reportsBox || !sectionBox || !budgetBox) {
			throw new Error('bounding boxes missing');
		}
		expect(sectionBox.y).toBeGreaterThan(reportsBox.y);
		expect(budgetBox.y).toBeGreaterThan(sectionBox.y);
	});
});
